import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const root = process.cwd();
const workflowPath = path.join(root, ".github", "workflows", "deploy-netcup.yml");
const nextPublisherPath = path.join(root, "ops", "netcup", "publish-next-app.sh");
const nextVerifierPath = path.join(root, "ops", "netcup", "verify-next-app.sh");

test("Netcup workflow deploys the current Next standalone app instead of stale Docusaurus build output", () => {
  const workflow = fs.readFileSync(workflowPath, "utf8");
  const verifier = fs.readFileSync(nextVerifierPath, "utf8");
  const packageJson = fs.readFileSync(path.join(root, "package.json"), "utf8");

  assert.match(workflow, /scripts\/standalone-assets\.mjs/);
  assert.match(workflow, /name: Generate runtime data[\s\S]*?run: npm run build:content/);
  assert.match(workflow, /run: npm test/);
  assert.match(workflow, /run: npm run lint/);
  assert.ok(workflow.indexOf("run: npm run build:content") < workflow.indexOf("run: npm test"));
  assert.equal(fs.existsSync(path.join(root, "data", "exams", "ssc-cgl", "resource-candidates.json")), true);
  assert.match(workflow, /npm run verify:ssc-render/);
  assert.match(packageJson, /"verify:ssc-browser":\s*"node scripts\/verify-ssc-browser-smoke\.mjs"/);
  assert.match(packageJson, /"verify:ssc-render":\s*"node --import tsx scripts\/verify-ssc-rendered-output\.ts"/);
  assert.match(workflow, /ops\/netcup\/publish-next-app\.sh/);
  assert.match(workflow, /chmod \+x ops\/netcup\/publish-next-app\.sh/);
  assert.match(workflow, /--exclude 'data\/auth\/'/);
  assert.match(workflow, /note-arzvak-predeploy-/);
  assert.match(workflow, /note-nginx-predeploy-/);
  assert.match(workflow, /chmod 600 .*note-arzvak-predeploy-/);
  assert.match(workflow, /--exclude 'data\/current-affairs\/'/);
  assert.doesNotMatch(workflow, /ssc-cgl-news|Install SSC CGL news cron|Refresh Next app after current-affairs/);
  assert.doesNotMatch(workflow, /docker compose -f docker-compose\.next\.yml up -d --no-build --force-recreate/);
  assert.doesNotMatch(workflow, /docker cp data\/current-affairs\/\. miteee-next-app:\/app\/data\/current-affairs\//);
  assert.doesNotMatch(workflow, /docker compose -f docker-compose\.next\.yml restart miteee-next/);
  assert.match(workflow, /ops\/netcup\/verify-next-app\.sh http:\/\/127\.0\.0\.1:3025/);
  assert.match(verifier, /deployment-auth-probe@invalid\.example/);
  assert.match(verifier, /test "\$auth_status" = "401"/);
  assert.doesNotMatch(workflow, /miteee-next-netcup-ports\.yml/);
  assert.doesNotMatch(workflow, /NETCUP_WEBROOT/);
  assert.doesNotMatch(workflow, /build\/\s*"\$NETCUP_USER@\$NETCUP_HOST:/);
  assert.doesNotMatch(workflow, /grep -q "MIT EEE"/);
  assert.match(verifier, /curl --fail[\s\S]*\/exams\/ssc-cgl/);
  assert.match(verifier, /grep -q "Build each subject\. Then test it\."/);
  assert.match(verifier, /grep -q "Four sections, clearly separated\."/);
  assert.match(verifier, /Legacy Study Vault label is still present/);
  assert.match(verifier, /subjects\/quantitative-aptitude/);
  assert.match(verifier, /The Quantitative Aptitude Notebook/);
  assert.match(verifier, /chapters\/number-system\/practice/);
  assert.match(verifier, /Reset chapter/);
  assert.match(verifier, /location: \/exams\/ssc-cgl\/practice\/number-system/);
  assert.match(verifier, /api\/exams\/ssc-cgl\/session\?mode=endless&section=quantitative-aptitude/);
  assert.match(verifier, /SSC CGL session corpus is empty/);
  assert.match(verifier, /payload\.questions\.length !== 1/);
  assert.match(verifier, /Library spaces/);
  assert.match(verifier, /Choose what you want to learn/);
  assert.match(verifier, /Make this study space yours/);
  assert.match(verifier, /Reader layout/);
  assert.match(verifier, /\/exams\/cat\/quant/);
  assert.match(verifier, /3,386/);
  assert.match(verifier, /\/exams\/gate/);
  assert.match(verifier, /Turn every GATE topic into a practice lane/);
  assert.match(verifier, /\/exams\/gate\/ee\/practice\/EE-S02-L008/);
  assert.match(verifier, /content-assets\/gate\/ee\/GATE-2024-EE-S8-Q13/);
  assert.match(verifier, /\/courses\/SEM7-EA/);
  assert.match(verifier, /Energy Auditing \(ELE 4446\)/);
  assert.match(verifier, /data\/generated\/notes-index\.json/);
  assert.match(verifier, /courseCode === "SEM7-EA"/);
  assert.match(verifier, /exactly 49 original notes/);
  assert.match(verifier, /203 unique note routes/);
  assert.match(verifier, /new Set\(energyNotes\.map\(\(note\) => note\.slug\)\)/);
  assert.match(verifier, /base_url\/notes\/\$ea_slug/);
  assert.match(verifier, /test "\$ea_note_status" = "200"/);
  assert.match(verifier, /grep -Fq -- "\$ea_title"/);
  assert.match(workflow, /ops\/netcup\/verify-next-app\.sh http:\/\/127\.0\.0\.1:3025/);
});

test("Netcup Next publisher restarts the live nginx-facing app instead of only syncing files", () => {
  const publisher = fs.readFileSync(nextPublisherPath, "utf8");
  const compose = fs.readFileSync(path.join(root, "docker-compose.next.yml"), "utf8");

  assert.match(publisher, /APP_PORT="\$\{NEXT_APP_PORT:-3025\}"/);
  assert.match(compose, /127\.0\.0\.1:\$\{NEXT_APP_PUBLISHED_PORT:-3000\}:3000/);
  assert.match(publisher, /export NEXT_APP_PUBLISHED_PORT="\$APP_PORT"/);
  assert.match(publisher, /chmod 700 "\$AUTH_DATA_DIR"/);
  assert.match(publisher, /find "\$AUTH_DATA_DIR" -maxdepth 1 -type f -exec chmod 600 \{\} \+/);
  assert.doesNotMatch(publisher, /miteee-next-netcup-ports\.yml/);
  assert.match(publisher, /systemctl stop "\$\{SERVICE_NAME\}\.service"/);
  assert.match(publisher, /systemctl disable "\$\{SERVICE_NAME\}\.service"/);
  assert.match(publisher, /\/etc\/systemd\/system\/\$\{SERVICE_NAME\}\.service/);
  assert.match(publisher, /WorkingDirectory=\$APP_DIR\/\.next\/standalone/);
  assert.match(publisher, /ExecStart=\$node_bin server\.js/);
  assert.match(publisher, /systemctl restart "\$\{SERVICE_NAME\}\.service"/);
  assert.match(publisher, /fuser -k "\$\{APP_PORT\}\/tcp"/);
  assert.match(publisher, /docker compose -f docker-compose\.next\.yml up -d --build/);
  assert.match(publisher, /http:\/\/\$\{APP_HOST\}:\$\{APP_PORT\}\/exams\/ssc-cgl/);
  assert.match(publisher, /http:\/\/\$\{APP_HOST\}:\$\{APP_PORT\}\/api\/auth\/get-session/);
  assert.match(publisher, /deployment-auth-probe@invalid\.example/);
  assert.match(publisher, /auth POST probe returned HTTP/);
  assert.match(publisher, /Next app did not become healthy/);
  assert.match(publisher, /refusing to report a stale deploy as successful/);
  assert.match(publisher, /nginx -t/);
  assert.match(publisher, /nginx -s reload/);
});

test("SSC CGL browser smoke verifier covers subjects, exam setup, timed sessions, and endless practice", () => {
  const script = fs.readFileSync(path.join(root, "scripts", "verify-ssc-browser-smoke.mjs"), "utf8");

  assert.match(script, /SSC_BROWSER_BASE_URL/);
  assert.match(script, /\/exams\/ssc-cgl/);
  assert.match(script, /\/exams\/ssc-cgl\/subjects\/reasoning/);
  assert.match(script, /Complete table of contents/);
  assert.match(script, /Build each subject\. Then test it\./);
  assert.match(script, /page\.goto\(`\$\{baseUrl\}\/practice`/);
  assert.match(script, /What do you want to practice\?/);
  assert.match(script, /Quick 10/);
  assert.match(script, /Section Test/);
  assert.match(script, /Full Mock/);
  assert.match(script, /Endless Practice/);
  assert.match(script, /Book \/ PYQ Practice/);
  assert.match(script, /Weakness Repair/);
  assert.match(script, /Configure your session/);
  assert.match(script, /Start Quick 10/);
  assert.match(script, /\/exams\/ssc-cgl\/session\?mode=quick/);
  assert.match(script, /Test sections/);
  assert.match(script, /Question palette/);
  assert.match(script, /Choose one answer/);
  assert.match(script, /Mark for review & next/);
  assert.match(script, /Answers and explanations stay hidden until you submit the test/);
  assert.match(script, /\/exams\/ssc-cgl\/session\?mode=endless/);
  assert.match(script, /No finish line\. Just focused repetitions\./);
  assert.match(script, /Check answer/);
  assert.match(script, /Next question/);
  assert.match(script, /horizontal overflow/);
  assert.match(script, /desktop/);
  assert.match(script, /mobile/);
});

test("Netcup and Docker builds include the promoted SSC CGL book corpus", () => {
  const dockerignore = fs.readFileSync(path.join(root, ".dockerignore"), "utf8");
  const gitignore = fs.readFileSync(path.join(root, ".gitignore"), "utf8");
  const promotedCorpusPath = path.join(root, "data", "exams", "ssc-cgl", "book-imports", "questions.json");
  const promotedCorpus = fs.statSync(promotedCorpusPath);

  assert.ok(promotedCorpus.size > 50_000_000);
  assert.doesNotMatch(dockerignore, /^data\/exams\/ssc-cgl\/book-imports\/questions\.json$/m);
  assert.doesNotMatch(gitignore, /^data\/exams\/ssc-cgl\/book-imports\/questions\.json$/m);
});
